// Registro central de ícones Hugeicons usados no projeto.
// Mapear por string permite guardar `icon_name` no banco (categorias) e
// resolver o componente correspondente na UI.
import {
  Album02Icon,
  Analytics01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  BookOpen01Icon,
  Hotel01Icon,
  Calendar03Icon,
  Cancel01Icon,
  ChurchIcon,
  Dumbbell01Icon,
  Facebook01Icon,
  FavouriteIcon,
  File01Icon,
  GlobalIcon,
  SquareLock02Icon,
  Shield01Icon,
  UserMultiple02Icon,
  Heading02Icon,
  Heading03Icon,
  Home01Icon,
  Image01Icon,
  ImageAdd01Icon,
  InstagramIcon,
  LeftToRightListBulletIcon,
  LeftToRightListNumberIcon,
  Link01Icon,
  Location01Icon,
  Login03Icon,
  Mail01Icon,
  MapsLocation01Icon,
  Megaphone01Icon,
  Menu01Icon,
  MountainIcon,
  Notification03Icon,
  News01Icon,
  ParagraphIcon,
  PlusSignIcon,
  QuoteDownIcon,
  Restaurant02Icon,
  Search01Icon,
  Settings01Icon,
  StarIcon,
  Tag01Icon,
  Tick02Icon,
  TextBoldIcon,
  TextClearIcon,
  TextItalicIcon,
  UserGroupIcon,
  UserIcon,
} from '@hugeicons/core-free-icons';

// Tipo do "SVG object" exportado pelo pacote de ícones.
export type IconData = typeof Home01Icon;

export const icons = {
  Home01Icon,
  News01Icon,
  Calendar03Icon,
  MountainIcon,
  ChurchIcon,
  Restaurant02Icon,
  Dumbbell01Icon,
  Hotel01Icon,
  MapsLocation01Icon,
  UserGroupIcon,
  Megaphone01Icon,
  Search01Icon,
  Menu01Icon,
  Cancel01Icon,
  StarIcon,
  FavouriteIcon,
  UserIcon,
  Login03Icon,
  Settings01Icon,
  Analytics01Icon,
  File01Icon,
  Tag01Icon,
  Image01Icon,
  Location01Icon,
  Mail01Icon,
  Notification03Icon,
  GlobalIcon,
  SquareLock02Icon,
  Shield01Icon,
  UserMultiple02Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  BookOpen01Icon,
  Facebook01Icon,
  InstagramIcon,
  // Editor de texto
  TextBoldIcon,
  TextItalicIcon,
  Heading02Icon,
  Heading03Icon,
  ParagraphIcon,
  LeftToRightListBulletIcon,
  LeftToRightListNumberIcon,
  QuoteDownIcon,
  Link01Icon,
  ImageAdd01Icon,
  Album02Icon,
  ArrowTurnBackwardIcon,
  ArrowTurnForwardIcon,
  TextClearIcon,
  PlusSignIcon,
  Tick02Icon,
} as const;

export type IconName = keyof typeof icons;

// Resolve um nome (possivelmente vindo do banco) para o ícone, com fallback.
export function resolveIcon(name: string | null | undefined, fallback: IconName = 'Tag01Icon'): IconData {
  if (name && name in icons) {
    return icons[name as IconName];
  }
  return icons[fallback];
}
