'use client';

import { useEffect, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import Button from '@/components/Button';
import ImageUploader from '@/components/ImageUploader';
import Input from '@/components/Input';
import Select from '@/components/Select';
import Textarea from '@/components/Textarea';
import ToggleSwitch from '@/components/ToggleSwitch';
import { deleteHomeSection, duplicateHomeSection, saveHomeSection, searchEligibleSectionPosts } from '@/features/homeSections/actions';
import { slugify } from '@/lib/utils/format';
import type { HomeSection } from '@/types/homeSections';

type SearchPost = { id: string; title: string; slug: string; published_at: string | null; cover_image_url: string | null; category: { name: string } | null; author: { full_name: string | null } | null };
type Form = { id?: string; title: string; subtitle: string; description: string; slug: string; status: 'active' | 'inactive'; display_order: number; placement_zone: 'after-hero' | 'after-latest-news' | 'before-events' | 'before-footer'; show_view_all: boolean; view_all_mode: 'internal' | 'custom' | 'hidden'; custom_view_all_url: string; cover_image_url: string; cover_image_alt: string; post_ids: string[] };
const empty = (): Form => ({ title: '', subtitle: '', description: '', slug: '', status: 'inactive', display_order: 0, placement_zone: 'after-latest-news', show_view_all: true, view_all_mode: 'internal', custom_view_all_url: '', cover_image_url: '', cover_image_alt: '', post_ids: [] });
const fromSection = (s: HomeSection, ids: string[] = []): Form => ({ id: s.id, title: s.title, subtitle: s.subtitle ?? '', description: s.description ?? '', slug: s.slug, status: s.status, display_order: s.display_order, placement_zone: s.placement_zone, show_view_all: s.show_view_all, view_all_mode: s.view_all_mode, custom_view_all_url: s.custom_view_all_url ?? '', cover_image_url: s.cover_image_url ?? '', cover_image_alt: s.cover_image_alt ?? '', post_ids: ids });

export default function HomeSectionManager({ sections, initialPosts }: { sections: HomeSection[]; initialPosts: Record<string, SearchPost[]> }) {
  const router = useRouter(); const [form, setForm] = useState<Form>(empty); const [results, setResults] = useState<SearchPost[]>([]); const [term, setTerm] = useState(''); const [error, setError] = useState<string | null>(null); const [pending, start] = useTransition();
  const selected = form.post_ids.map((id) => [...Object.values(initialPosts).flat(), ...results].find((post) => post.id === id) ?? { id, title: 'Post selecionado', slug: '', published_at: null, cover_image_url: null, category: null, author: null });
  useEffect(() => { const timer = window.setTimeout(() => start(async () => { const r = await searchEligibleSectionPosts(term); if (r.ok) setResults(r.posts as unknown as SearchPost[]); }), 350); return () => window.clearTimeout(timer); }, [term]);
  function patch(values: Partial<Form>) { setForm((current) => ({ ...current, ...values })); }
  function choose(post: SearchPost) { if (!form.post_ids.includes(post.id)) patch({ post_ids: [...form.post_ids, post.id] }); }
  function move(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= form.post_ids.length) return; const ids = [...form.post_ids]; const current = ids[index]; const next = ids[target]; if (!current || !next) return; ids[index] = next; ids[target] = current; patch({ post_ids: ids }); }
  function edit(section: HomeSection) { setForm(fromSection(section, initialPosts[section.id]?.map((post) => post.id) ?? [])); setError(null); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function save() { setError(null); start(async () => { const r = await saveHomeSection({ ...form, selection_mode: 'manual' }); if (!r.ok) return setError(r.error ?? 'Erro ao salvar.'); setForm(empty()); router.refresh(); }); }
  function remove(id: string, title: string) { if (!window.confirm(`Excluir “${title}”? Os posts originais não serão excluídos.`)) return; start(async () => { const r = await deleteHomeSection(id); if (!r.ok) setError(r.error ?? 'Erro ao excluir.'); else router.refresh(); }); }
  return <div className="space-y-6">
    <section className="card-base space-y-4 p-4 sm:p-5">
      <div><h2 className="font-bold text-title">{form.id ? 'Editar seção' : 'Nova seção'}</h2><p className="text-xs text-muted">Salve incompleta como inativa; para ativar, inclua posts públicos.</p></div>
      <div className="grid gap-3 sm:grid-cols-2"><Input label="Título" value={form.title} onChange={(e) => patch({ title: e.target.value, slug: form.id ? form.slug : slugify(e.target.value) })} /><Input label="Slug" value={form.slug} onChange={(e) => patch({ slug: slugify(e.target.value) })} /><Input label="Subtítulo" value={form.subtitle} onChange={(e) => patch({ subtitle: e.target.value })} /><Input label="Ordem" type="number" value={String(form.display_order)} onChange={(e) => patch({ display_order: Number(e.target.value) })} /><Select label="Posição na home" value={form.placement_zone} onChange={(e) => patch({ placement_zone: e.target.value as Form['placement_zone'] })} options={[{ value: 'after-hero', label: 'Após o destaque' }, { value: 'after-latest-news', label: 'Após últimas notícias' }, { value: 'before-events', label: 'Antes dos eventos' }, { value: 'before-footer', label: 'Antes do rodapé' }]} /><Select label="Status" value={form.status} onChange={(e) => patch({ status: e.target.value as Form['status'] })} options={[{ value: 'inactive', label: 'Inativa' }, { value: 'active', label: 'Ativa' }]} /></div>
      <Textarea label="Descrição (na página pública)" rows={3} value={form.description} onChange={(e) => patch({ description: e.target.value })} />
      <div className="grid gap-3 sm:grid-cols-2"><ImageUploader bucket="section-covers" prefix="home" value={form.cover_image_url || null} onChange={(url) => patch({ cover_image_url: url ?? '' })} label="Imagem de capa" compact /><Input label="Texto alternativo da capa" value={form.cover_image_alt} onChange={(e) => patch({ cover_image_alt: e.target.value })} /></div>
      <ToggleSwitch label="Exibir link “Ver tudo”" checked={form.show_view_all} onChange={(show_view_all) => patch({ show_view_all })} />
      {form.show_view_all && <div className="grid gap-3 sm:grid-cols-2"><Select label="Destino do link" value={form.view_all_mode} onChange={(e) => patch({ view_all_mode: e.target.value as Form['view_all_mode'] })} options={[{ value: 'internal', label: 'Página da seção' }, { value: 'custom', label: 'URL personalizada' }, { value: 'hidden', label: 'Ocultar' }]} />{form.view_all_mode === 'custom' && <Input label="URL" value={form.custom_view_all_url} onChange={(e) => patch({ custom_view_all_url: e.target.value })} />}</div>}
      <div className="border-t border-line pt-4"><label className="block text-sm font-semibold text-title">Selecionar posts publicados</label><Input aria-label="Buscar posts" value={term} onChange={(e) => setTerm(e.target.value)} placeholder="Buscar pelo título" /><div className="mt-2 max-h-44 overflow-y-auto rounded-lg border border-line">{results.map((post) => <button key={post.id} type="button" onClick={() => choose(post)} disabled={form.post_ids.includes(post.id)} className="flex w-full items-center justify-between gap-3 border-b border-line px-3 py-2 text-left text-sm hover:bg-surface disabled:opacity-50"><span className="truncate font-medium text-title">{post.title}<span className="ml-2 text-xs text-muted">{post.category?.name}</span></span><span>{form.post_ids.includes(post.id) ? 'Selecionado' : 'Adicionar'}</span></button>)}{!pending && results.length === 0 && <p className="p-3 text-sm text-muted">Nenhum post encontrado.</p>}</div></div>
      <div><h3 className="text-sm font-semibold text-title">Posts selecionados ({selected.length})</h3><ol className="mt-2 divide-y divide-line rounded-lg border border-line">{selected.map((post, index) => <li key={post.id} className="flex items-center gap-2 p-2"><span className="w-5 text-xs text-muted">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-medium text-title">{post.title}</span><button type="button" onClick={() => move(index, -1)} disabled={!index} className="rounded border border-line px-2 py-1 text-xs disabled:opacity-40" aria-label={`Mover ${post.title} para cima`}>↑</button><button type="button" onClick={() => move(index, 1)} disabled={index === selected.length - 1} className="rounded border border-line px-2 py-1 text-xs disabled:opacity-40" aria-label={`Mover ${post.title} para baixo`}>↓</button><button type="button" onClick={() => patch({ post_ids: form.post_ids.filter((id) => id !== post.id) })} className="text-xs text-danger">Remover</button></li>)}{selected.length === 0 && <li className="p-3 text-sm text-muted">Nenhum post selecionado.</li>}</ol></div>
      {error && <p role="alert" className="text-sm text-danger">{error}</p>}<div className="flex flex-wrap gap-2"><Button onClick={save}>{pending ? 'Salvando...' : form.id ? 'Salvar alterações' : 'Criar seção'}</Button>{form.id && <Button variant="ghost" onClick={() => setForm(empty())}>Cancelar edição</Button>}</div>
    </section>
    <section className="card-base overflow-x-auto"><table className="w-full text-sm"><thead className="bg-surface text-left text-xs text-muted"><tr><th className="p-3">Seção</th><th className="p-3">Status</th><th className="p-3">Posição</th><th className="p-3">Posts</th><th className="p-3" /></tr></thead><tbody className="divide-y divide-line">{sections.map((section) => <tr key={section.id}><td className="p-3"><span className="block font-semibold text-title">{section.title}</span><span className="text-xs text-muted">/secoes/{section.slug}</span></td><td className="p-3">{section.status === 'active' ? 'Ativa' : 'Inativa'}</td><td className="p-3">{section.placement_zone} · {section.display_order}</td><td className="p-3">{initialPosts[section.id]?.length ?? 0}</td><td className="whitespace-nowrap p-3 text-right"><button onClick={() => edit(section)} className="text-xs text-brand">Editar</button><button onClick={() => start(async () => { await duplicateHomeSection(section.id); router.refresh(); })} className="ml-3 text-xs text-brand">Duplicar</button>{section.status === 'active' && <a href={`/secoes/${section.slug}`} target="_blank" className="ml-3 text-xs text-brand">Ver</a>}<button onClick={() => remove(section.id, section.title)} className="ml-3 text-xs text-danger">Excluir</button></td></tr>)}{sections.length === 0 && <tr><td colSpan={5} className="p-5 text-center text-muted">Nenhuma seção criada.</td></tr>}</tbody></table></section>
  </div>;
}
